name: NAT-Whitelist
version: ${version}
main: fr.Nat0uille.NATWhitelist.Main
api-version: '1.21'
load: STARTUP
authors: [ Nat0uille ]
commands:
  whitelist:
    aliases:
      - wl
      - nat-whitelist
    usage: /<command> <add|remove|list|> [<player>]
permissions:
  natwhitelist.reload:
    default: op
  natwhitelist.add:
    default: op
  natwhitelist.remove:
    default: op
  natwhitelist.on:
    default: op
  natwhitelist.off:
    default: op
  natwhitelist.removeoffline:
    default: op
  natwhitelist.admin:
    default: op
    children:
      natwhitelist.reload: true
      natwhitelist.add: true
      natwhitelist.remove: true
      natwhitelist.on: true
      natwhitelist.off: true
      natwhitelist.removeoffline: true