name: NAT-Whitelist
version: ${version}
main: fr.Nat0uille.NATWhitelist.Main
api-version: '1.21'
load: STARTUP
authors: [ Nat0uille ]
commands:
  whitelist:
    aliases: wl
    usage: /<command> <add|remove|list|> [<player>]
permissions:
  NatWhitelist.Use:
    default: op