name: NAT-Whitelist
version: ${version}
main: fr.Nat0uille.NATWhitelist.Main
api-version: '1.21'
load: STARTUP
authors: [ Nat0uille ]
commands:
  whitelist:
    aliases:
      - wl
      - nat-whitelist
permissions:
  natwhitelist.reload:
    description: Reload the plugin configuration
  natwhitelist.add:
    description: Add players to whitelist
  natwhitelist.remove:
    description: Remove players from whitelist
  natwhitelist.on:
    description: Enable the whitelist
  natwhitelist.off:
    description: Disable the whitelist
  natwhitelist.removeoffline:
    description: Remove offline players from whitelist
  natwhitelist.bypass:
    description: Bypass the whitelist
  natwhitelist.list:
    description: List all whitelisted players
  natwhitelist.admin:
    description: All permissions
    default: op
    children:
      natwhitelist.reload: true
      natwhitelist.add: true
      natwhitelist.remove: true
      natwhitelist.on: true
      natwhitelist.off: true
      natwhitelist.removeoffline: true
      natwhitelist.bypass: true
      natwhitelist.list: true
  natwhitelist.*:
    description: All permissions
    children:
      - natwhitelist.admin