name: NAT-Whitelist
version: ${version}
main: fr.Nat0uille.NATWhitelist.Main
api-version: '1.21'
load: STARTUP
authors: [ Nat0uille ]
Commands:
  whitelist:
    alias: wl
    usage: /<command>
Permissions:
  NatWhitelist.Use:
    default: op